# Generated by Django 2.2.24 on 2021-11-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('thumbnail', models.ImageField(default='stream/stream.png', upload_to='stream/')),
                ('description', models.TextField()),
            ],
        ),
    ]
