# Generated by Django 2.2.24 on 2021-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to='movies/')),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('released', models.DateField()),
            ],
        ),
    ]
