# Generated by Django 2.2.24 on 2021-11-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('thumbnail', models.ImageField(default='production/default.png', upload_to='production/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.ManyToManyField(default=1, to='movies.Production'),
        ),
    ]
