# Generated by Django 2.2.24 on 2021-11-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211111_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='platform',
            field=models.ManyToManyField(blank=True, to='stream.Stream'),
        ),
    ]
