# Generated by Django 2.2.24 on 2021-11-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20211111_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Released', 'Released'), ('Digital', 'Digital')], default='Released', max_length=50),
        ),
    ]
